### ISSUE TITLE
Some files don't fully resolve.

### ISSUE THREAD

**Issue by allanhortle** [dadish/sass-import-resolve#1]
Some files will return only the literal import path. With neither the _ or the suffixes.

```
'/src/structure/flood.sass',
'/src/structure/_flood.sass',
'/src/structure/flood.scss',
'/src/structure/_flood.scss',
'/src/structure/grid',
'/src/structure/hide',
'/src/structure/ratio.sass',
'/src/structure/_ratio.sass',
'/src/structure/ratio.scss',
'/src/structure/_ratio.scss'
```

**Comment by dadish** [comment]
@allanhortle could you please post the contents of the file that gives this result. So I could reproduce the bug.

**Comment by dadish** [comment]
@allanhortle

**Comment by allanhortle** [comment]
I was building a webpack loader for sassdoc. They work a little different to each other so I am using sass-import-resolve to stitch them both together:

https://github.com/allanhortle/bruce/blob/master/lib/sassdoc-loader/index.js

The file I was parsing is:

https://github.com/allanhortle/bruce/blob/master/bruce.scss

you can see the culprits that have had their `_` and `.scss` added back in.

**Comment by dadish** [comment]
I think I fixed it. I made a patch and published to npm.
You can do

``` bash
$ npm uninstall sass-import-resolve --save
$ npm install sass-import-resolve --save
```

at your `bruce/lib/sassdoc-loader/` and the issue should be gone.

Please confirm.

**Comment by dadish** [comment]
@allanhortle

**Comment by allanhortle** [comment]
Sorry for the late response. It works perfectly! 
Lets me publish the module: https://www.npmjs.com/package/sassdoc-loader
Thanks heaps.
